"""App version - GENERATED from package.json by scripts/sync_version.py.

package.json is the one file a release bumps; do not edit this file by
hand (every build regenerates it, so manual changes are silently lost).
"""
__version__ = "0.20.0"
