#!/usr/bin/env python3
"""Regenerate backend/_version.py from package.json (the canonical version).

package.json is the ONE file a release bumps. This script re-derives the
backend's view of the version so the two can never drift: build_sidecar.sh
and build_server.sh run it before PyInstaller, so shipped binaries always
embed the same version as the package.json the release was cut from.

The committed backend/_version.py exists only so dev runs (uvicorn, pytest)
work without invoking this script first — a build regenerates it, so any
manual edit there is silently lost by design.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent


def main() -> int:
    pkg = json.loads((ROOT / "package.json").read_text(encoding="utf-8"))
    version = pkg.get("version")
    if not isinstance(version, str) or not version:
        print("sync_version: package.json has no usable version field", file=sys.stderr)
        return 1
    target = ROOT / "backend" / "_version.py"
    target.write_text(
        '"""App version - GENERATED from package.json by scripts/sync_version.py.\n'
        "\n"
        "package.json is the one file a release bumps; do not edit this file by\n"
        "hand (every build regenerates it, so manual changes are silently lost).\n"
        '"""\n'
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )
    print(f"sync_version: backend/_version.py -> {version}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
